# Generated by Django 3.0.8 on 2020-09-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='TITLE', max_length=30)),
                ('date', models.DateTimeField(default='28/9/20')),
                ('text_area', models.TextField(default='random text lorem ipsum lipsum jipsum kipsum hiphum jism jism 2')),
            ],
        ),
    ]
